default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "postgres" } %>
  database: <%= ENV.fetch("DATABASE_NAME") { "task_manager_be_development" } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME") { "task_manager_be_test" } %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
